new workflow

diff --git a/.github/workflows/push-pull.yml b/.github/workflows/push-pull.yml
--- a/.github/workflows/push-pull.yml
+++ b/.github/workflows/push-pull.yml
@@ -1,35 +1,86 @@
-name: Translation Workflow
+name: Push and Pull Translations
 on:
   pull_request:
-    branches:
-      - main
+    types: [opened]
     paths:
       - "locales/**en.json"
 jobs:
-  build:
+  push-translations:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
+      - name: Checkout Repository
+        uses: actions/checkout@v3
         with:
+          ref: ${{ github.head_ref }}
           fetch-depth: 0
       - name: Lokalise CLI
-        run: curl -sfL https://raw.githubusercontent.com/lokalise/lokalise-cli-2-go/master/install.sh | sh
-      - name: Push
-        env:
-          VAR_LOKALISE_API_TOKEN: ${{ secrets.LOKALISE_API_TOKEN }}
-          VAR_LOKALISE_PROJECT_ID: ${{ secrets.LOKALISE_PROJECT_ID }}
-          ENV_LOKALISE_SOURCE_LANG_ISO: en
         run: |
-          while read file
-          do
-             if [ -f $file ]
-             then
-               ./bin/lokalise2 --token $VAR_LOKALISE_API_TOKEN --project-id $VAR_LOKALISE_PROJECT_ID file upload --file="${file}" --lang-iso $ENV_LOKALISE_SOURCE_LANG_ISO --replace-modified --include-path --use-automations=true --cleanup-mode --poll-timeout 120s
-             fi
-          done < <(
-          if [ -z ${{ github.event.before }} ]
+          curl -sfL https://raw.githubusercontent.com/lokalise/lokalise-cli-2-go/master/install.sh | sh -s -- -b $HOME/bin
+          if [ -f $HOME/bin/lokalise2 ]
           then
-           git ls-files -- 'locales/**${ENV_LOKALISE_SOURCE_LANG_ISO}.json'
+            echo "Lokalise CLI installed successfully"
           else
-           git diff --name-only ${{ github.event.after }} ${{ github.event.before }} -- 'locales/**${ENV_LOKALISE_SOURCE_LANG_ISO}.json'
+            echo "Lokalise CLI installation failed"
+            exit 1
+          fi
+      - name: Push translations to Lokalise
+        env:
+          LOKALISE_API_TOKEN: ${{ secrets.LOKALISE_API_TOKEN }}
+          LOKALISE_PROJECT_ID: ${{ secrets.LOKALISE_PROJECT_ID }}
+          LOKALISE_SOURCE_LANG_ISO: en
+        run: |
+          while read file 
+          do 
+            if [ -f $file ]
+            then
+              $HOME/bin/lokalise2 --token ${{ env.LOKALISE_API_TOKEN }} --project-id ${{ env.LOKALISE_PROJECT_ID }} file upload --file="${file}" --lang-iso ${{ env.LOKALISE_SOURCE_LANG_ISO }} --replace-modified --include-path --use-automations=true --cleanup-mode --poll-timeout 120s
+            fi
+          done < <(
+          if [ -z ${{ github.event.after }} ]
+          then
+            git ls-files -- 'locales/**${{ env.LOKALISE_SOURCE_LANG_ISO }}.json'
+          else
+            git diff --name-only ${{ github.event.before }} ${{ github.event.after }} -- 'locales/**${{ env.LOKALISE_SOURCE_LANG_ISO }}.json'
           fi | awk NF)
+
+  pull-translations:
+    runs-on: ubuntu-latest
+    needs: push-translations
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+      - name: Fetch base branch
+        run: git fetch origin ${{ github.base_ref }}:$GITHUB_BASE_BRANCH
+        env:
+          GITHUB_BASE_BRANCH: ${{ github.base_ref }}
+      - name: Lokalise CLI
+        run: |
+          curl -sfL https://raw.githubusercontent.com/lokalise/lokalise-cli-2-go/master/install.sh | sh -s -- -b $HOME/bin
+          if [ -f $HOME/bin/lokalise2 ]
+          then
+            echo "Lokalise CLI installed successfully"
+          else
+            echo "Lokalise CLI installation failed"
+            exit 1
+          fi
+      - name: Pull translations from Lokalise
+        env:
+          GH_TOKEN: ${{ github.token }}
+          LOKALISE_API_TOKEN: ${{ secrets.LOKALISE_API_TOKEN }}
+          LOKALISE_PROJECT_ID: ${{ secrets.LOKALISE_PROJECT_ID }}
+        run: |
+          $HOME/bin/lokalise2 --token ${{ env.LOKALISE_API_TOKEN }} --project-id ${{ env.LOKALISE_PROJECT_ID }} file download --format json --original-filenames=true --directory-prefix=/
+          NEW_BRANCH="translations-update-${GITHUB_RUN_ID}"
+          git checkout -b $NEW_BRANCH $GITHUB_BASE_BRANCH
+          git push origin $NEW_BRANCH
+          git config --global user.name "${GITHUB_ACTOR}"
+          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
+          git add locales/*.json
+          if [[ -z $(git status --untracked-files=no --porcelain) ]]
+          then
+            echo "No changes"
+          else
+            git commit -m "Translations update"
+            git push origin $NEW_BRANCH
+            gh pr create --base $GITHUB_BASE_BRANCH --head "$NEW_BRANCH" --title "Translations Update" --body "This pull request updates translations."
+          fi
